### PR TITLE
Cart example refactor: remove graphql filter, move pub key to env

### PR DESCRIPTION
**Pull request by tjgilpin**
To get the cart example at URL /advanced working and remove build warnings this

* Moves stripe publishable key to .env
* Removes graphql product id filter
* Sets gatsby-plugin-stripe plugin downloadFiles: false to remove build warning
* Sets node version

### CODE REVIEW

**Comment by thorsten-stripe** [comment]
Thanks for this! I really should refactor this to use function components and hooks...

**Comment by tjgilpin** [comment]
> Thanks for this! I really should refactor this to use function components and hooks...

No worries, 👍 for a function components and hooks refactor

**Comment by thorsten-stripe** [comment]
fyi: https://github.com/thorsten-stripe/ecommerce-gatsby-tutorial/pull/24

**Comment by tjgilpin** [comment]
> fyi: #24

@thorsten-stripe - looks very nice, keen to check it out soon 👍

**Pull request merged**
